monty:
	mkdir -p bin
	g++ --std=c++17 -o bin/monty src/monty.cpp	
none:
	./bin/monty

cat:
	./bin/monty cat

test16:
	./bin/monty 16

test100:
	./bin/monty 100

test2000:
	./bin/monty 2000

test10000:
	./bin/monty 10000

clean:
	rm -rf bin

